# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Build documentation in the doc/ directory with Sphinx
sphinx:
  configuration: doc/source/conf.py
  fail_on_warning: false

# Build all formats (HTML, PDF, ePub)
formats:
  - pdf
  - epub

# Python version and build environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - pandoc
  jobs:
    post_checkout:
      # Fetch full git history for setuptools_scm version detection
      - git fetch --unshallow || true

# Python dependencies
# Note: We skip installing the package itself to avoid building C++ extensions
# Sphinx will use autodoc_mock_imports for the C++ modules
python:
  install:
    - requirements: doc/requirements.txt
